"""add vendor delivery_date status notes columns

Revision ID: fce9c23a22c8
Revises: e3d426d6ff95
Create Date: 2026-05-06 13:42:56.512837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce9c23a22c8'
down_revision: Union[str, Sequence[str], None] = 'e3d426d6ff95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('vendor', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'delivery_date')
    op.drop_column('orders', 'vendor')
    # ### end Alembic commands ###
